// Keyed by 4-digit EMPLOYEE ID (used for login)
export const MOCK_USERS = {
    '1001': {
        empId: '1001',
        password: '1234',
        name: 'Rabindra Kumar Sahoo',
        role: 'Super_admin',
        branches: ['Bangalore', 'Mangalore', 'Ranchi'],
        designation: 'IT Manager',
        department: 'Information Technology',
        email: 'superadmin@marutiflex.com',
        phone: '+91 98765 43210',
        _id: '65f1a2b3c4d5e6f7a8b9c001',
        token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWYxYTJiM2M0ZDVlNmY3YThiOWMwMDEiLCJyb2xlIjoiU3VwZXJfYWRtaW4iLCJpYXQiOjE3MTEwMDAwMDB9.SUPER_ADMIN_SIGNATURE_XYZ123'
    },
    '1002': {
        empId: '1002',
        password: '1234',
        name: 'Arjun Kapoor',
        role: 'Admin',
        branches: ['Bangalore', 'Mangalore'],
        designation: 'Operations Head',
        department: 'Operations',
        email: 'admin@marutiflex.com',
        phone: '+91 98765 43211',
        _id: '65f1a2b3c4d5e6f7a8b9c002',
        token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWYxYTJiM2M0ZDVlNmY3YThiOWMwMDIiLCJyb2xlIjoiQWRtaW4iLCJpYXQiOjE3MTEwMDAwMDB9.ADMIN_SIGNATURE_ABC456'
    },
    '1003': {
        empId: '1003',
        password: '1234',
        name: 'Priya Sharma',
        role: 'Management',
        branches: ['Bangalore'],
        designation: 'Director',
        department: 'Management',
        email: 'management@marutiflex.com',
        phone: '+91 98765 43212',
        _id: '65f1a2b3c4d5e6f7a8b9c003',
        token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWYxYTJiM2M0ZDVlNmY3YThiOWMwMDMiLCJyb2xlIjoiTWFuYWdlbWVudCIsImlhdCI6MTcxMTAwMDAwMH0.MANAGEMENT_SIG_DEF789'
    },
    '1004': {
        empId: '1004',
        password: '1234',
        name: 'Anita Desai',
        role: 'HR_manager',
        branches: ['Bangalore', 'Mangalore'],
        designation: 'HR Manager',
        department: 'Human Resources',
        email: 'hrmanager@marutiflex.com',
        phone: '+91 98765 43213',
        _id: '65f1a2b3c4d5e6f7a8b9c004',
        token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWYxYTJiM2M0ZDVlNmY3YThiOWMwMDQiLCJyb2xlIjoiSFJfbWFuYWdlciIsImlhdCI6MTcxMTAwMDAwMH0.HR_MGR_SIG_GHI012'
    },
    '1005': {
        empId: '1005',
        password: '1234',
        name: 'Kavita Rao',
        role: 'HR_executive',
        branches: ['Bangalore'],
        designation: 'HR Executive',
        department: 'Human Resources',
        email: 'hrexec@marutiflex.com',
        phone: '+91 98765 43214',
        _id: '65f1a2b3c4d5e6f7a8b9c005',
        token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWYxYTJiM2M0ZDVlNmY3YThiOWMwMDUiLCJyb2xlIjoiSFJfZXhlY3V0aXZlIiwiaWF0IjoxNzExMDAwMDAwfQ.HR_EXEC_SIG_JKL345'
    },
    '1006': {
        empId: '1006',
        password: '1234',
        name: 'Suresh Nair',
        role: 'Manager',
        branches: ['Mangalore'],
        designation: 'Operations Manager',
        department: 'Operations',
        email: 'manager@marutiflex.com',
        phone: '+91 98765 43215',
        _id: '65f1a2b3c4d5e6f7a8b9c006',
        token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWYxYTJiM2M0ZDVlNmY3YThiOWMwMDYiLCJyb2xlIjoiTWFuYWdlciIsImlhdCI6MTcxMTAwMDAwMH0.MANAGER_SIG_MNO678'
    },
    '1007': {
        empId: '1007',
        password: '1234',
        name: 'Vikram Singh',
        role: 'Team_leader',
        branches: ['Bangalore'],
        designation: 'Team Lead',
        department: 'Engineering',
        email: 'teamlead@marutiflex.com',
        phone: '+91 98765 43216',
        _id: '65f1a2b3c4d5e6f7a8b9c007',
        token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWYxYTJiM2M0ZDVlNmY3YThiOWMwMDciLCJyb2xlIjoiVGVhbV9sZWFkZXIiLCJpYXQiOjE3MTEwMDAwMDB9.TEAM_LEAD_SIG_PQR901'
    },
    '1008': {
        empId: '1008',
        password: '1234',
        name: 'Rahul Mehta',
        role: 'Employee',
        branches: ['Ranchi'],
        designation: 'Software Engineer',
        department: 'Engineering',
        email: 'employee@marutiflex.com',
        phone: '+91 98765 43217',
        _id: '65f1a2b3c4d5e6f7a8b9c008',
        token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWYxYTJiM2M0ZDVlNmY3YThiOWMwMDgiLCJyb2xlIjoiRW1wbG95ZWUiLCJpYXQiOjE3MTEwMDAwMDB9.EMPLOYEE_SIG_STU234'
    },
}