import { ROLES } from './roles'

// Map which roles can see which sidebar link
export const LINK_ACCESS = {
    'Dashboard': [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGEMENT, ROLES.HR_MANAGER, ROLES.HR_EXECUTIVE, ROLES.MANAGER, ROLES.TEAM_LEADER, ROLES.EMPLOYEE],
    'Workforce': [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGEMENT, ROLES.HR_MANAGER, ROLES.HR_EXECUTIVE],
    'Payroll': [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HR_MANAGER],
    'Attendance': [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGEMENT, ROLES.HR_MANAGER, ROLES.HR_EXECUTIVE, ROLES.MANAGER, ROLES.TEAM_LEADER, ROLES.EMPLOYEE],
    'Recruitment': [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HR_MANAGER, ROLES.HR_EXECUTIVE],
    'Onboarding': [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HR_MANAGER, ROLES.HR_EXECUTIVE],
    'Exit Process': [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HR_MANAGER],
    'MIS Reports': [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGEMENT, ROLES.MANAGER],
    'Expenses': [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGEMENT, ROLES.HR_MANAGER, ROLES.HR_EXECUTIVE, ROLES.MANAGER, ROLES.TEAM_LEADER, ROLES.EMPLOYEE],
    'Assets': [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HR_MANAGER, ROLES.MANAGER],
    'Helpdesk': [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HR_MANAGER, ROLES.HR_EXECUTIVE, ROLES.MANAGER, ROLES.TEAM_LEADER, ROLES.EMPLOYEE],
    'Master': [ROLES.SUPER_ADMIN, ROLES.ADMIN],
}